// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/prediction-cards/Glow.tsx": () => import("../components/mockups/prediction-cards/Glow.tsx"),
  "./components/mockups/prediction-cards/Scorecard.tsx": () => import("../components/mockups/prediction-cards/Scorecard.tsx"),
  "./components/mockups/prediction-cards/Ticket.tsx": () => import("../components/mockups/prediction-cards/Ticket.tsx")
};
